djangonetninja/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',views.home,name="home"),
    path('',views.home),
    #musicapp
    path('music/',include('music.urls')),
    #hello to name
    path('<str:name>/',views.types)
]

music/urls.py
from django.urls import path
from . import views
from .models import Album

app_name = "music"

urlpatterns = [
        #music/
        path('',views.index,name="music"),
        # music/album
        path('album/',views.albums,name="album"),
        #music/album/1
        path('album/<int:album_id>',views.album,name="album_detail"),
        #music/song
        path('song/',views.songs,name="song"),
        #music/song/1
        path('song/<int:song_id>',views.song,name="song_detail"),
        #artist/
        path('artist/',views.artists,name="artist"),
        #artist/1
        path('artist/<str:artist_name>',views.artist,name="artist_detail"),
]

music/models.py
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=100)
    album_title = models.CharField(max_length=100)
    genre = models.CharField(max_length=50)
    album_logo = models.CharField(max_length=500)

    def __str__(self):
        return self.album_title + " - " + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title =models.CharField(max_length=100)
    def __str__(self):
        return self.song_title

djangonetninja/views.py
from django.http import HttpResponse

def home(request):
    return HttpResponse("home")

def about(request):
    return HttpResponse('about')

def types(request,name):
    Name = name.capitalize()
    return HttpResponse(f'Hello, <span style="color:blue;">{Name}</span>')

music/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Album, Song


# def error(request,lol):
#     context = {
#         "error":lol,
#     }
#     return render(request,"music/error.html",context)


def index(request):
    page_title = "Music"
    context = {
        "page_title": page_title,
    }
    return render(request, "music/index.html", context)


def albums(request):
    all_albums = Album.objects.all()
    page_title = "Albums"
    context = {
        'all_albums': all_albums,
        'page_title': page_title,
    }
    return render(request, "music/all_albums.html", context)


def album(request, album_id):
    try:
        a = Album.objects.get(id=album_id)
        songs = a.song_set.all()
        page_title = a.album_title
        context = {
            "page_title": page_title,
            "album": a,
            "songs": songs,
            'a':request,
        }
        return render(request, "music/album_details.html", context)
    except (Album.DoesNotExist):
        page_title = "Error In Album"
        error = "No such Album"
        context = {
            "error":error,
            "page_title":page_title,
        }
        return render(request,"music/error.html",context)


def songs(request):
    a = False
    a = Song.objects.order_by("album__artist").all()
    page_title = "Songs"
    context = {
        "page_title": page_title,
        "songs": a,
    }
    return render(request, "music/songs.html", context)


def song(request, song_id):
    try:
        a = Song.objects.get(id=song_id)
        page_title = a.song_title
        context = {
            "page_title": page_title,
            "song_details": a,
        }
        return render(request,"music/song_details.html",context)
    except (Song.DoesNotExist):
        error = "No Such song"
        context = {
            "page_title": "Error No Song",
            "error":error,
        }
        return render(request,"music/error.html",context)

def artists(request):
    a = Album.objects.order_by('artist').all()
    singers=[]
    for b in a:
        container =  b.artist
        if container in singers:
            continue
        singers.append(container)

    page_title = "Artists"
    context = {
        "page_title":page_title,
        "artists": singers,
    }
    return render(request,"music/artists.html" , context)

def artist(request,artist_name):
    try:
        b = Album.objects.filter(artist=artist_name).first()
        a = Album.objects.filter(artist= artist_name)
        page_title  = b.artist
        context = {
            "page_title":page_title,
            "albums":a,
        }
        return render (request,'music/artist_detail.html',context)
    except (Album.DoesNotExist,AttributeError):
        page_title="Error Artist"
        context = {
            "page_title":page_title,
            "error":"No such artist or does not exist in database!"
        }
        return render(request,"music/error.html",context)

    return False

music/templates/music/album_details.html
{% extends 'music/layout.html' %}
{% block body %}
<img src="{{album.album_logo}}" alt="">
<div>Album Title : {{album.album_title}}</div>
<div>Artist : {{album.artist}}</div>
<ul>
    {% for song in songs %}
    <li><a style="text-decoration: none;" href="{% url 'music:song_detail' song.id %}">{{song.song_title}} -
            {{song.file_type}}</a></li>
    {%endfor%}
</ul>
{% endblock %}

music/templates/music/all_albums.html
{% extends 'music/layout.html' %}
{% block body %}
<div class="container" style="text-align: center;">
        <h2>All Album</h2>
</div>
<div class="container">
        <div class="music-div" style="overflow-x:auto;">
                <div class="row justify-content-lg-center">
                        {% for album in all_albums %}
                        <div class="col-4" style="text-align:center; padding:3em 0em; ">
                                <a href="{% url 'music:album_detail' album.id %}"><img height="150px" width="150px"
                                                src="{{album.album_logo}}" alt="album1"></a>
                                <div><span class="bold">Artist</span> : {{album.artist}}</div>
                                <div><span class="bold">Album Title</span> : {{album.album_title}}</div>
                        </div>
                        {%endfor%}
                </div>

        </div>
</div>
{% endblock %}

music/templates/music/artist_detail.html
{% extends 'music/layout.html' %}
{% block body %}
<img src="https://scontent.frgn5-1.fna.fbcdn.net/v/t1.0-9/s960x960/79092909_1108882206170007_8423633200600842240_o.jpg?_nc_cat=1&_nc_sid=85a577&_nc_eui2=AeFtkztX1H8fqS4y3tsOum5ufeRUYPVXjkl95FRg9VeOSaLU7EsoLRDZ1J0Jio8qYw4W3SsxOgyovQDE3TEJNbid&_nc_ohc=YTTzaDM3OWQAX_slrhi&_nc_ht=scontent.frgn5-1.fna&_nc_tp=7&oh=c6ce25905c1e760446dbde668b7bbf75&oe=5EB00CD0"
    alt="" height="150px" width="150px">
<h4>{{albums.first.artist}}</h4>
<ul>
    {% for artist in albums %}
    <li>
        <a href="{% url 'music:album_detail' artist.id %}">
            {{artist.album_title}}
        </a>
    </li>
    <ul>
        {% for song in artist.song_set.all %}
        <li>
            <a href="{% url 'music:song_detail' song.id %}">
                {{song.song_title}}
            </a>
        </li>
        {% endfor %}
    </ul>
    {% endfor %}
</ul>

{% endblock %}

music/templates/music/artists.html
{% extends 'music/layout.html' %}
{% block body %}
{% for artist in artists %}
<ul>
    <li>
        <a href="{% url 'music:artist_detail' artist %}">
            {{artist}}
        </a>
    </li>
</ul>
{% endfor %}
{% endblock %}

music/templates/music/error.html
{% extends 'music/layout.html' %}
{% block body %}
<h2>{{error}}</h2>
{% endblock %}

music/templates/music/index.html
{% extends 'music/layout.html' %}
{% block body %}
    <div class="container">
        <h1 style="text-align: center; color:blue;">Welcome from my music channel</h1>
        <div>
            <div><a href="{% url 'music:album' %}">All Albums</a></div>
            <div><a href="{% url 'music:song' %}">All Songs</a></div>
        </div>
    </div>
{% endblock %}

music/templates/music/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {{page_title}}
    </title>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <script src="{% static 'music/app.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'music/styles.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">


</head>

<body>
    <div class="container-fluid" style="background-color:gray; margin:0px; padding:0px;">
        <nav class="navbar navbar-expand-lg navbar-light bg-light nav-color">
            <a class="navbar-brand" href="{% url 'music:music' %}">Sighefio</a>
            <button id="stoggle" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span id="stoggle-icon" class="material-icons">menu</span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'music:music' %}">Home <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'music:artist' %}">Artists</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'music:album' %}">Albums</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'music:song' %}">Song</a>
                    </li>
                </ul>
                <div>
                    <a href="#"><span class="material-icons" style="vertical-align: middle;">add_box</span> Add Album</a>
                    <a href="#" style="margin-left: 15px;"><span class="material-icons" style="vertical-align: middle;">logout</span> Logout</a>
                </div>
            </div>
        </nav>
    </div>
    {% block body %}
    {% endblock %}


</body>

</html>

music/templates/music/song_details.html
{% extends 'music/layout.html' %}
{% block body %}
    <h2>{{song_details.song_title}}</h2>
    <ul>
        <li>Artist :  <a href="{% url 'music:artist_detail' song_details.album.artist %}">{{song_details.album.artist}}</a></li>
        <li>Album : <a href="{% url 'music:album_detail' song_details.album.id %}">{{song_details.album.album_title}}</a>  (<a href="{% url 'music:music' %}">{{song_details.album.genre}}</a>)</li>
    </ul>
    {% endblock %}

music/templates/music/songs.html
{% extends 'music/layout.html' %}
{% block body %}
<h2>All songs</h2>
<div class="container">
    <div class="row">
        {% for song in songs %}
        <div class="col-12" style="box-sizing:border-box; max-height:100px; border:1px solid black; padding:5px;">
            <div class="row">
            <a class="col-7" style="text-decoration: none;" href="{% url 'music:song_detail' song.id %}">{{song.song_title}} -
                {{song.file_type}}</a><a style="text-align: right;" class="col-5" href="{% url 'music:artist_detail' song.album.artist %}"> ( {{song.album.artist}} )</a>
        </div>
    </div>
        {%endfor%}
    </div>
</div>
{% endblock %}